spring:
  application:
    name: authentication-api
  profiles:
    active: local
  banner:
    location: classpath:banner/banner.txt
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_URL}:3306/${DB_NAME}?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: ${DB_ID}
    password: ${DB_PASSWORD}
  jpa:
    database: mysql
    generate-ddl: true
    show-sql: true

springfox:
  documentation:
    swagger:
      v2:
        use-model-v3: false

portal:
  jsoup:
    connection:
      url: https://portal.sookmyung.ac.kr/irj/portal
      userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
      header:
        origin: https://portal.sookmyung.ac.kr
        referer: https://portal.sookmyung.ac.kr/irj/portal
        accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
        contentType: application/x-www-form-urlencoded
        acceptEncoding: gzip, deflate, br
        acceptLanguage: ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7

security:
  access-token-valid-second: 1000000000
  jwtCookieName: ${JWT_NAME}
  jwtSecret: ${JWT_SECRET}

